title: G R Krishna Chand Avatar
position: Ph.D. Student
affiliation: Indian Institute of Science, Bengaluru (India)
email: krishnaagr (at) iisc (dot) ac (dot) in
keywords: minimal academic
google_scholar: https://scholar.google.com/ag8-zTIAAAAJ
github_link: https://github.com/kcavatar
linkedin: https://www.linkedin.com/in/kcavatar
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.jpg
favicon_dark: ./assets/img/favicon.jpg
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: kcavatar/minimal-light
